//Estados de fetch al api de videojuegos
export const FETCH_API_GAMES_REQUEST = 'FETCH_API_GAMES_REQUEST';
export const FETCH_API_GAMES_SUCCESS = 'FETCH_API_GAMES_SUCCESS';
export const FETCH_API_GAMES_FAILURE = 'FETCH_API_GAMES_FAILURE';
export const SUCCESS_STATUS_API_GAMES = 'SUCCESS_STATUS_API_GAMES';
export const GET_GAME_BY_ID = 'GET_GAME_BY_ID';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_FAILURE = 'ADD_GAME_FAILURE';
export const ADD_GAME_REQUEST = 'ADD_GAME_REQUEST';
export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
//Estados de fetch al api de generos
export const FETCH_API_GENRES_REQUEST = 'FETCH_API_GENRES_REQUEST';
export const FETCH_API_GENRES_SUCCESS = 'FETCH_API_GENRES_SUCCESS';
export const FETCH_API_GENRES_FAILURE = 'FETCH_API_GENRES_FAILURE';
export const SUCCESS_STATUS_API_GENRES = 'SUCCESS_STATUS_API_GENRES';
//Estados de fetch al api de plataformas
export const FETCH_API_PLATFORMS_REQUEST = 'FETCH_API_PLATFORMS_REQUEST';
export const FETCH_API_PLATFORMS_SUCCESS = 'FETCH_API_PLATFORMS_SUCCESS';
export const FETCH_API_PLATFORMS_FAILURE = 'FETCH_API_PLATFORMS_FAILURE';
//Manejo del front
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PAGE_CURRENT_GAMES = 'SET_PAGE_CURRENT_GAMES';
export const SET_PAGE_ALL_GAMES = 'SET_PAGE_ALL_GAMES';
export const DELETE_GAME_FROM_FRONT = 'DELETE_GAME_FROM_FRONT';
export const ADD_GAME_TO_FRONT = 'ADD_GAME_TO_FRONT';
//Manejo de los filtros
export const SET_ORDERING = 'SET_ORDERING';
export const SET_FILTER_ORIGEN = 'SET_FILTER_ORIGEN';
export const SET_FILTER_GENRES = 'SET_FILTER_GENRES';
export const SET_FILTER_SEARCH = 'SET_FILTER_SEARCH';
export const SET_FILTER_RATING = 'SET_FILTER_RATING';



